### ISSUE TITLE
Asymmetric Focal Length

### ISSUE THREAD

**Issue by sam598** [joreeves/mr2nerf#1]
Focal Lengths in the output transforms.json came out like so:

```
"fl_x": 3282.2516711791563,
"fl_y": 5842.794435803687,
```

For the dataset I was testing "fl_x" looked right, but usually "fl_y" is the same value so it seemed strange. When testing in intant-ngp in never converged. When I manually set "fl_y" to the same value it converged.

Looking at the sfm.json I generated from meshroom it looks like there's only a single value for focal length (I assume in millimeters). Is the script converting based on this value and scaling based on image dimensions?

**Comment by joreeves** [comment]
Could you send me your input json? I can take a look. There is an issue
with different lens types I haven’t fully looked at yet, could be that.
