### ISSUE TITLE
I tried the script on a few 100 shots from my phone and got this:

### ISSUE THREAD

**Issue by sgawad** [joreeves/mr2nerf#3]
Hello,
first time trying this so bare with me please and sorry if I don't really get the instructions..
I am not really sure what to do with the manual transform though is there something I need to enter in the SfMTransform (manual) Translation x y z or Euler Rotation? I left everything to 0 in doubt.

2023-07-30 00:39:07 | INFO | font_manager.py : 1544 | >>> generated new fontManager
2023-07-30 00:39:10 | WARNING | mr2nerf.py : 109 | >>> W/H ratio does not match sensor ratio, this is likely a bug from Meshroom. Will use fl_x to set fl_y.
Traceback (most recent call last):
  File "C:\Users\Shady\Documents\mr2nerf\mr2nerf.py", line 226, in <module>
    camera['transform_matrix'] = transforms[poseId]
                                 ~~~~~~~~~~^^^^^^^^
KeyError: '137075643'

![image](https://github.com/joreeves/mr2nerf/assets/5367483/7ae44230-b56b-430e-b0f3-cf7b848f1426)

**Comment by joreeves** [comment]
Based on your error message, it looks as though one of the poses is missing a transform matrix. Would you be able to share your json file. It likely doesn't have anything to do with the SfMTransform.

**Comment by avclubvids** [comment]
Oh, I know this one well. @sgawad:

Double-click on the SfMTransform node to view it in the viewer. It will appear under the StructureFromMotion, which you can remove or turn its visibility toggle off (the eye icon to the left of it). Then you should have an XYZ transform gizmo that you can rotate and move to relocate the SfMTransform's version of the point cloud. Move it first, then rotate it, because it is a pain to rotate then move.

**Comment by sgawad** [comment]
Dear @joreeves,
here is the zip of the 144Mb (json file that was produced)... wonder why it is so large...
[sfm.zip](https://github.com/joreeves/mr2nerf/files/12210084/sfm.zip)


and here is an exerpt of the begining:
{
    "version": [
        "1",
        "2",
        "4"
    ],
    "featuresFolders": [
        "..\\..\\FeatureExtraction\\0f1f93e5241931004eda3d26c5af7ee9ee7c489b"
    ],
    "matchesFolders": [
        "..\\..\\FeatureMatching\\aa52dfb024d322ee7c47f2d9411267ae031b19d0"
    ],
    "views": [
        {
            "viewId": "6467022",
            "poseId": "6467022",
            "frameId": "11",
            "intrinsicId": "2248852245",
            "resectionId": "46",
            "path": "C:\/cat\/11.jpg",
            "width": "1440",
            "height": "3200",
            "metadata": {
                "AliceVision:SensorWidth": "6.400000",
                "DateTime": "2023:07:23 11:37:11",
                "Exif:ApertureValue": "2.27",
                "Exif:BrightnessValue": "5.41",
                "Exif:ColorSpace": "1",
                "Exif:DateTimeDigitized": "2023:07:23 11:37:11",
                "Exif:DateTimeOriginal": "2023:07:23 11:37:11",
                "Exif:ExifVersion": "0220",
                "Exif:ExposureBiasValue": "0",
                "Exif:ExposureMode": "0",
                "Exif:ExposureProgram": "2",
                "Exif:Flash": "16",
                "Exif:FlashPixVersion": "0100",
                "Exif:FocalLength": "2.13",
                "Exif:FocalLengthIn35mmFilm": "12",
                "Exif:MaxApertureValue": "2.27",
                "Exif:MeteringMode": "2",
                "Exif:OffsetTimeOriginal": "-07:00",
                "Exif:PhotographicSensitivity": "100",
                "Exif:PixelXDimension": "0",
                "Exif:PixelYDimension": "0",
                "Exif:SceneCaptureType": "0",
                "Exif:SceneType": "1",
                "Exif:SensingMethod": "1",
                "Exif:ShutterSpeedValue": "8.406",
                "Exif:SubsecTime": "919",
                "Exif:SubsecTimeDigitized": "919",
                "Exif:SubsecTimeOriginal": "919",
                "Exif:WhiteBalance": "0",
                "Exif:YCbCrPositioning": "1",
                "ExposureTime": "0.00294985",
                "FNumber": "2.2",
                "ICCProfile": "0, 0, 2, 36, 97, 112, 112, 108, 4, 0, 0, 0, 109, 110, 116, 114, 82, 71, 66, 32, 88, 89, 90, 32, 7, 226, 0, 6, 0, 24, 0, 13, 0, 22, 0, 32, 97, 99, 115, 112, 65, 80, 80, 76, 0, 0, 0, 0, 79, 80, 80, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ... [548 x uint8]",
                "ICCProfile:attributes": "Reflective, Glossy, Positive, Color",
                "ICCProfile:cmm_type": "1634758764",
                "ICCProfile:color_space": "RGB",
                "ICCProfile:copyright": "Copyright Apple Inc., 2017",
                "ICCProfile:creation_date": "2018:06:24 13:22:32",
                "ICCProfile:creator_signature": "6170706c",
                "ICCProfile:device_class": "Display device profile",
                "ICCProfile:flags": "Not Embedded, Independent",
                "ICCProfile:manufacturer": "4f50504f",
                "ICCProfile:model": "0",
                "ICCProfile:platform_signature": "Apple Computer, Inc.",
                "ICCProfile:profile_connection_space": "XYZ",
                "ICCProfile:profile_description": "Display P3",
                "ICCProfile:profile_size": "548",
                "ICCProfile:profile_version": "4.0.0",
                "ICCProfile:rendering_intent": "Perceptual",
                "Make": "OPPO",
                "Model": "OPPO Reno2",
                "Orientation": "1",
                "ResolutionUnit": "none",
                "XResolution": "72",
                "YResolution": "72",
                "jpeg:subsampling": "4:2:0",
                "oiio:ColorSpace": "sRGB"
            }
        },
        {
            "viewId": "83378721",
            "poseId": "83378721",
            "frameId": "36",
            "intrinsicId": "2248852245",
            "resectionId": "28",
            "path": "C:\/cat\/36.jpg",
            "width": "1440",
            "height": "3200",
            "metadata": {
                "AliceVision:SensorWidth": "6.400000",
                "DateTime": "2023:07:23 11:38:38",
                "Exif:ApertureValue": "2.27",
                "Exif:BrightnessValue": "4.04",
                "Exif:ColorSpace": "1",
                "Exif:DateTimeDigitized": "2023:07:23 11:38:38",
                "Exif:DateTimeOriginal": "2023:07:23 11:38:38",
                "Exif:ExifVersion": "0220",
                "Exif:ExposureBiasValue": "0",
                "Exif:ExposureMode": "0",
                "Exif:ExposureProgram": "2",
                "Exif:Flash": "16",
                "Exif:FlashPixVersion": "0100",
                "Exif:FocalLength": "2.13",
                "Exif:FocalLengthIn35mmFilm": "12",
                "Exif:MaxApertureValue": "2.27",
                "Exif:MeteringMode": "2",
                "Exif:OffsetTimeOriginal": "-07:00",
                "Exif:PhotographicSensitivity": "100",
                "Exif:PixelXDimension": "0",
                "Exif:PixelYDimension": "0",
                "Exif:SceneCaptureType": "0",
                "Exif:SceneType": "1",
                "Exif:SensingMethod": "1",
                "Exif:ShutterSpeedValue": "6.658",
                "Exif:SubsecTime": "392",
                "Exif:SubsecTimeDigitized": "392",
                "Exif:SubsecTimeOriginal": "392",
                "Exif:WhiteBalance": "0",
                "Exif:YCbCrPositioning": "1",
                "ExposureTime": "0.00990099",
                "FNumber": "2.2",
                "ICCProfile": "0, 0, 2, 36, 97, 112, 112, 108, 4, 0, 0, 0, 109, 110, 116, 114, 82, 71, 66, 32, 88, 89, 90, 32, 7, 226, 0, 6, 0, 24, 0, 13, 0, 22, 0, 32, 97, 99, 115, 112, 65, 80, 80, 76, 0, 0, 0, 0, 79, 80, 80, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ... [548 x uint8]",
                "ICCProfile:attributes": "Reflective, Glossy, Positive, Color",
                "ICCProfile:cmm_type": "1634758764",
                "ICCProfile:color_space": "RGB",
                "ICCProfile:copyright": "Copyright Apple Inc., 2017",
                "ICCProfile:creation_date": "2018:06:24 13:22:32",
                "ICCProfile:creator_signature": "6170706c",
                "ICCProfile:device_class": "Display device profile",
                "ICCProfile:flags": "Not Embedded, Independent",
                "ICCProfile:manufacturer": "4f50504f",
                "ICCProfile:model": "0",
                "ICCProfile:platform_signature": "Apple Computer, Inc.",
                "ICCProfile:profile_connection_space": "XYZ",
                "ICCProfile:profile_description": "Display P3",
                "ICCProfile:profile_size": "548",
                "ICCProfile:profile_version": "4.0.0",
                "ICCProfile:rendering_intent": "Perceptual",
                "Make": "OPPO",
                "Model": "OPPO Reno2",
                "Orientation": "1",
                "ResolutionUnit": "none",
                "XResolution": "72",
                "YResolution": "72",
                "jpeg:subsampling": "4:2:0",
                "oiio:ColorSpace": "sRGB"
            }
        },
        
@avclubvids , Yep I managed to move and rotate just as you said, thanks for the trick but do I really want to? I don't mind if the whole world is rotated for now... just getting a nerf is good enough for me, I will be able to change it later if I manage to have the file processed without errors.

**Comment by joreeves** [comment]
@sgawad So, it looks like there were a few images without any pose/transform in your json. I've added a check that will skip over these if they are encountered. The images in question were:
`114, 119, 117, 115, 122, 120, 121, 116, 118`

Please try with the new updates and let me know if everything is working.

**Comment by avclubvids** [comment]
@sgawad - you can also make a much smaller sfm.json if you only check the Views, Intrinsics, and Extrinsics options in the ConvertSfMFormat node. And I see that cctag4 is checked in the SfMTransform node - unless you do actually have cctags in the photos I would de-select that upstream as you don't need to run that detection unless you have visible tags to detect.

**Comment by sgawad** [comment]
Wow, Thanks for your support and all the advices ;) !!!
